=== amillet2001/WMA4A-MT-LAB-EX/asio_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="studentPortfolio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" type="student"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="student">
        <xs:sequence>
            <xs:element name="personalInfo" type="personalInfo"/>
            <xs:element name="skills" type="skills"/>
            <xs:element name="projects" type="projects"/>
            <xs:element name="contact" type="contact"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="personalInfo">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="program" type="xs:string"/>
            <xs:element name="about" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="skills">
        <xs:sequence>
            <xs:element name="skill" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="projects">
        <xs:sequence>
            <xs:element name="project" type="project" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="project">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="contact">
        <xs:sequence>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="socials" type="socials"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="socials">
        <xs:sequence>
            <xs:element name="github" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== amillet2001/WMA4A-MT-LAB-EX/asio_portfolio.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="asio_transform.xsl"?>
<studentPortfolio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="asio_schema.xsd">

    <student>
        <personalInfo>
            <name>Shanielle Anne Asio</name>
            <email>shanielleanne27@gmail.com</email>
            <program>BS Information Technology</program>

            <about>
                Hi! My name is Shanielle Anne Asio. I am a 4th-year IT student passionate about web development and design.
            </about>
        </personalInfo>

        <skills>
            <skill>HTML</skill>
            <skill>CSS</skill>
            <skill>JavaScript</skill>
            <skill>Python</skill>
            <skill>PHP, MySQL, and SQL</skill>
            <skill>Figma</skill>
            <skill>Flutter</skill>
            <skill>Git</skill>
            <skill>Ionic</skill>
        </skills>

        <projects>
            <project>
                <title>Gourmet Discoveries</title>
                <description>A web application that allows users to explore Filipino cuisines.</description>
            </project>
        </projects>

        <contact>
            <email>shanielleanne27@gmail.com</email>
            <socials>
                <github>shnll-a</github>
            </socials>
        </contact>

    </student>
</studentPortfolio>
