=== amillet2001/WMA4A-MT-LAB-EX/Batomalaque_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <!-- Root element -->
    <xs:element name="portfolio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" type="studentType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- student -->
    <xs:complexType name="studentType">
        <xs:sequence>
            <xs:element name="name" type="nameType"/>
            <xs:element name="contact" type="contactType"/>
            <xs:element name="skills" type="skillsType"/>
            <xs:element name="project" type="projectType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- name -->
    <xs:complexType name="nameType">
        <xs:sequence>
            <xs:element name="first" type="xs:string"/>
            <xs:element name="last" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <!-- contact -->
    <xs:complexType name="contactType">
        <xs:sequence>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="photo" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <!-- skills -->
    <xs:complexType name="skillsType">
        <xs:sequence>
            <xs:element name="skill" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- project -->
    <xs:complexType name="projectType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="year" type="xs:gYear"/>

            <xs:element name="images" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="img" type="xs:string" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== amillet2001/WMA4A-MT-LAB-EX/Batomalaque_portfolio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Batomalaque_transform.xsl"?>
<portfolio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="Batomalaque_schema.xsd">

    <student id="2025-01">
        <name>
            <first>Vance Levin</first>
            <last>Batomalaque</last>
        </name>

        <contact>
            <email>bvancelevin05@gmail.com</email>
            <photo>Batomalaque_images/batomalaque.jpg</photo>
        </contact>

        <skills>
            <skill>HTML</skill>
            <skill>CSS</skill>
            <skill>JavaScript</skill>   
            <skill>React JS</skill>
        </skills>

        <project>
            <title>VisioLearn Quiz Generator</title>
            <year>2025</year>
                        <images>
    <img>Batomalaque_images/img1.png</img>
    <img>Batomalaque_images/img2.png</img>
    <img>Batomalaque_images/img3.png</img>
</images>
        </project>
    </student>

</portfolio>
