=== amillet2001/WMA4A-MT-LAB-EX/dequiros_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="student_portfolio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student">
                    <xs:complexType>
                        <xs:sequence>
                            
                            <xs:element name="student_name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="first_name" type="xs:string"/>
                                        <xs:element name="second_name" type="xs:string" minOccurs="0"/>
                                        <xs:element name="middle_name" type="xs:string"/>
                                        <xs:element name="last_name" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="student_number" type="xs:string"/>
                            <xs:element name="student_email" type="xs:string"/>
                            
                            <xs:element name="student_course">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="program" type="xs:string"/>
                                        <xs:element name="specialization" type="xs:string"/>
                                        <xs:element name="year" type="xs:string"/>
                                        <xs:element name="section" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="college" type="xs:string"/>
                            <xs:element name="date_of_birth" type="xs:string"/>

                            <xs:element name="skills">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="skill" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== amillet2001/WMA4A-MT-LAB-EX/dequiros_portfolio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="dequiros_transform.xsl"?>
<student_portfolio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dequiros_schema.xsd">
    
    <student>
        <student_name>
            <first_name>Allen </first_name>
            <second_name>Icee </second_name>
            <middle_name>Aquino </middle_name>
            <last_name>Dequiros</last_name>
        </student_name>
        <student_number>2022300238</student_number>
        <student_email>ai.dequiros00238@student.tsu.edu.ph</student_email>
        <student_course>
            <program>Bachelor of Science in Information Technology (BSIT)</program>
            <specialization>Web and Mobile Application</specialization>
            <year>4th Year</year>
            <section>WMA-4A</section>
        </student_course>
        <college>College of Computer Studies (TSU)</college>
        <date_of_birth>October 30, 2003</date_of_birth>
        
        <skills>
            <skill>Cisco Certified Network Associate (CCNA 1 &amp; 2)</skill>
            <skill>Java Programming</skill>
            <skill>Web Development (HTML, CSS, JS)</skill>
            <skill>Visual Basic</skill>
            <skill>Multimedia (Krita, Capcut, IbisPaint)</skill>
        </skills>

    </student>
    
</student_portfolio>
