=== amillet2001/WMA4A-MT-LAB-EX/Ligsay_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="studentPortfolio">
    <xs:complexType>
        <xs:sequence>

            <xs:element name="student">
                <xs:complexType>
                    <xs:sequence>

                        <xs:element name="name">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="firstName" type="xs:string"/>
                                    <xs:element name="secondName" type="xs:string"/>
                                    <xs:element name="middleName" type="xs:string"/>
                                    <xs:element name="lastName" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

                        <xs:element name="studentNumber" type="xs:string"/>
                        <xs:element name="studentEmail" type="xs:string"/>

                        <xs:element name="course">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="program" type="xs:string"/>
                                    <xs:element name="major" type="xs:string"/>
                                    <xs:element name="year" type="xs:string"/>
                                    <xs:element name="section" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        
                        <xs:element name="skills">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="skill" type="xs:string" maxOccurs="unbounded"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

                        <xs:element name="achievements">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="certificate" type="xs:string" />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            
        </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== amillet2001/WMA4A-MT-LAB-EX/Ligsay_portfolio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Ligsay_transform.xsl"?>
<studentPortfolio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ligsay_schema.xsd">
    <student>
        <name>
            <firstName>Dave</firstName>
            <secondName>Joshua</secondName>
            <middleName>Corpuz</middleName>
            <lastName>Ligsay</lastName>
        </name>
        <studentNumber>2022300585</studentNumber>
        <studentEmail>dj.ligsay00585.tsu.edu.ph</studentEmail>
        <course>
            <program>Bachelor of Science in Information Technology</program>
            <major>Web and Mobile Application</major>
            <year>4th Year</year>
            <section>WMA-4A</section>
        </course>
        <skills>
            <skill>Java</skill>
            <skill>HTML</skill>
            <skill>CSS</skill>
            <skill>JavaScript</skill>
        </skills>
        <achievements>
            <certificate>CISCO 1 &amp; 2 Certificate</certificate>
        </achievements>
    </student>
</studentPortfolio>
