=== amillet2001/WMA4A-MT-LAB-EX/marimla_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="portfolio">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="student">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="name" type="xs:string"/>
              <xs:element name="age" type="xs:string"/>
              <xs:element name="course" type="xs:string"/>
              <xs:element name="year" type="xs:integer"/>

              <xs:element name="skills">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="skill" type="xs:string" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="projects">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="project" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="title" type="xs:string"/>
                          <xs:element name="description" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== amillet2001/WMA4A-MT-LAB-EX/marimla_portfolio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="marimla_transform.xsl"?>

<portfolio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="marimla_schema.xsd">

    <student>
        <name>John Michael C. Marimla</name>
        <course>BSIT-WMA 4A</course>
        <age>21</age>
        <year>4</year>

        <skills>
            <skill>Java</skill>
            <skill>HTML</skill>
            <skill>JS</skill>
            <skill>CSS</skill>
            <skill>PHP</skill>
        </skills>

        <projects>
            <project>
                <title>MEOWMATES</title>
                <description>A Cat Health and Tips Blog</description>
            </project>

            <project>
                <title>REVIO</title>
                <description>A Reviewer Material Generator with Study Techniques</description>
            </project>
        </projects>
    </student>

</portfolio>
