=== amillet2001/WMA4A-MT-LAB-EX/mina_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="student">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fullname" type="xs:string"/>
                <xs:element name="age" type="xs:integer"/>
                <xs:element name="address" type="xs:string"/>
                <xs:element name="course" type="xs:string"/>
                <xs:element name="yearlevel" type="xs:string"/>
                <xs:element name="studentID" type="xs:string"/>
                <xs:element name="email" type="xs:string"/>
                <xs:element name="phone" type="xs:string"/>

                <xs:element name="skills">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="skill" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="hobbies">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hobby" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="motto" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== amillet2001/WMA4A-MT-LAB-EX/mina_portfolio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="mina_transform.xsl"?>
<student xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="mina_schema.xsd">

    <fullname>Mark Denver D. Mina</fullname>
    <age>21</age>
    <address>Brgy. Castillo, Concepcion, Tarlac</address>
    <course>BSIT specialized in Web and Mobile Application</course>
    <yearlevel>4th Year</yearlevel>
    <studentID>2022300493</studentID>
    <email>minamarkdenver@gmail.com</email>
    <phone>09951297546</phone>
    <skills>
        <skill>Time Management</skill>
        <skill>Critical Thinking</skill>
        <skill>Communication Skills</skill>
    </skills>
    <hobbies>
        <hobby>Watching movies/series</hobby>
        <hobby>Scrolling on Social Media Platforms</hobby>
    </hobbies>
    <motto>The best is yet to come.</motto>

</student>
