=== amillet2001/WMA4A-MT-LAB-EX/ocampo_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="portfolio">
        <xsd:complexType>
            <xsd:sequence>

                <xsd:element name="student">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="firstname" type="xsd:string"/>
                            <xsd:element name="lastname" type="xsd:string"/>
                            <xsd:element name="course" type="xsd:string"/>
                            <xsd:element name="year" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="skills">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="skill" type="xsd:string" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="projects">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="project" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="title" type="xsd:string"/>
                                        <xsd:element name="description" type="xsd:string"/>
                                        <xsd:element name="year" type="xsd:gYear"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== amillet2001/WMA4A-MT-LAB-EX/ocampo_portfolio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="ocampo_transform.xsl"?>

<portfolio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="ocampo_schema.xsd">

    <student>
        <firstname>Kenzo Lian</firstname>
        <lastname>Ocampo</lastname>
        <course>BS Information Technology</course>
        <year>4th Year</year>
    </student>

    <skills>
        <skill>HTML and CSS</skill>
        <skill>JavaScript</skill>
        <skill>Java Programming</skill>
        <skill>UI/UX Design</skill>
    </skills>

    <projects>
        <project>
            <title>SyntaxSensei</title>
            <description>A web platform to help students in learning Java Programming</description>
            <year>2025</year>
        </project>
    </projects>

</portfolio>
