=== amillet2001/WMA4A-MT-LAB-EX/sarmiento_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="studentPortfolio">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="student">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="firstName" type="xs:string"/>
                    <xs:element name="secondName" type="xs:string"/>
                    <xs:element name="middlename" type="xs:string"/>
                    <xs:element name="lastName" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="studentNumber" type="xs:string"/>
              <xs:element name="studentEmail" type="xs:string"/>

              <xs:element name="course">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="program" type="xs:string"/>
                    <xs:element name="major" type="xs:string"/>
                    <xs:element name="year" type="xs:string"/>
                    <xs:element name="section" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="achievements">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="cert" type="xs:string" maxOccurs="unbounded"/>
                    <xs:element name="award" type="xs:string" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="hobbies">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="hobby" type="xs:string" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== amillet2001/WMA4A-MT-LAB-EX/sarmiento_portfolio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="sarmiento_transform.xsl"?>
<studentPortfolio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="sarmiento_schema.xsd">

    <student>
        <name>
            <firstName> Sandara</firstName>
            <secondName>Nicole</secondName>
            <middlename>Bonifacio</middlename>
            <lastName>Sarmiento </lastName>
        </name>

        <studentNumber> 2022300234</studentNumber>
        <studentEmail> sn.sarmiento00235@student.tsu.edu.ph</studentEmail>

        <course>
            <program> Bachelor of Science in Information Technology</program>
            <major> Web and Mobile Application</major>
            <year> 4th Year</year>
            <section> WMA-4A</section>
        </course>

        <achievements>
            <cert> Software Development Life Cycle &amp; 1 Certificate</cert>
            <cert> Basic Cisco Networking &amp; 1 Certificate</cert>
            <cert> Introduction to Linux &amp; 1 Certificate</cert>
            <award> Dean's Lister since 1st year &amp; CCS</award>
            <award> Girls Basketball MVP Intramurals 2023</award>
        </achievements>

        <hobbies>
            <hobby> Reading Books</hobby>
            <hobby> Music Streaming</hobby>
            <hobby> Netflix Streaming</hobby>
            <hobby> Studying</hobby>
        </hobbies>

    </student>

</studentPortfolio>
